# Generated by Django 5.0.2 on 2024-03-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('establishment_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('establishment_name', models.CharField(help_text='Nome que aparecerá na interface do usuário.', max_length=45, verbose_name='Nome Fantasia')),
                ('establishment_legal_name', models.CharField(help_text='Nome registrado oficialmente nos documentos legais e registros comerciais.', max_length=45, verbose_name='Razão Social')),
                ('establishment_cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('establishment_address', models.CharField(max_length=45, verbose_name='Endereço')),
                ('establishment_description', models.CharField(help_text='Uma breve descrição do comércio.', max_length=255, verbose_name='Descrição')),
                ('establishment_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('establishment_ddd_phone', models.CharField(max_length=3, verbose_name='DDD')),
                ('establishment_phone', models.CharField(max_length=9, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
    ]
